{
	"id": "CVE-2020-24583",
	"vulnerabilities": [
		{
			"id": "CVE-2020-24583",
			"references": [
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.alpinelinux.org/vuln/CVE-2020-24583"
				}
			]
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:3.12",
			"vulnerable": true,
			"package": {
				"name": "py3-django",
				"repositories": [
					"main"
				],
				"architectures": [
					"aarch64",
					"armhf",
					"armv7",
					"mips64",
					"ppc64le",
					"s390x",
					"x86",
					"x86_64"
				]
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.11.29-r1"
					}
				],
				"fixed": [
					"1.11.29-r1"
				]
			}
		}
	],
	"data_source": "alpine-secdb"
}
